package exporter

import (
	"fmt"
	"strings"

	"github.com/Zyrexnn/serahkan-cli/internal/report"
)

func ExportMarkdown(data ReportData) (string, error) {
	content := StripANSI(data.AISummary)
	sections := report.Parse(content)

	timestamp := data.Timestamp.Format("2006-01-02 15:04:05 UTC")

	var md strings.Builder
	md.WriteString("# SERAHKAN CLI - Security Report\n\n")
	md.WriteString("**AI-Powered Security Analysis Report**\n\n")
	md.WriteString("---\n\n")
	md.WriteString("## Scan Metadata\n\n")
	md.WriteString(fmt.Sprintf("| Field | Value |\n"))
	md.WriteString(fmt.Sprintf("|-------|-------|\n"))
	md.WriteString(fmt.Sprintf("| Target | `%s` |\n", data.Target))
	md.WriteString(fmt.Sprintf("| Findings | %d |\n", data.FindingCount))
	md.WriteString(fmt.Sprintf("| AI Analysis | %s |\n", data.AIStatus))
	md.WriteString(fmt.Sprintf("| Duration | %s |\n", data.ScanDuration))
	md.WriteString(fmt.Sprintf("| Generated | %s |\n\n", timestamp))
	md.WriteString("---\n\n")
	if len(sections) == 0 {
		md.WriteString("## Executive Summary\n\n")
		md.WriteString("```\n")
		md.WriteString(content)
		md.WriteString("\n```\n\n")
	} else {
		for _, section := range sections {
			md.WriteString(fmt.Sprintf("## %s\n\n", section.Title))
			if section.Content != "" {
				md.WriteString(section.Content)
				md.WriteString("\n\n")
			}
			for _, item := range section.Items {
				switch {
				case item.IsCode:
					md.WriteString("```\n")
					md.WriteString(item.Value)
					md.WriteString("\n```\n\n")
				case item.IsBullet:
					md.WriteString(fmt.Sprintf("- %s\n", item.Value))
				case item.Key != "":
					md.WriteString(fmt.Sprintf("- **%s:** %s\n", item.Key, item.Value))
				}
			}
			if len(section.Items) > 0 {
				md.WriteString("\n")
			}
		}
	}
	md.WriteString("---\n\n")
	md.WriteString("*Report generated by SERAHKAN CLI - github.com/Zyrexnn/serahkan-cli*\n")

	filename := GenerateFilename(data.Target, "md")
	savedPath, err := SaveToFile(filename, []byte(md.String()))
	if err != nil {
		return "", err
	}

	return savedPath, nil
}
